# Generated by Django 5.2.14 on 2026-05-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text="e.g., 'ankori-project-karen'", unique=True)),
                ('description', models.TextField(help_text='Main welcome text and introduction')),
                ('address', models.CharField(help_text='Full street address', max_length=255)),
                ('neighborhood', models.CharField(default='Nairobi', help_text='e.g., Karen, Lavington', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10)),
                ('status', models.CharField(choices=[('now_selling', 'Now Selling'), ('under_development', 'Under Development'), ('ready_to_move_in', 'Ready to Move In')], default='now_selling', max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('area_sqft', models.IntegerField(default=0, help_text='Area in Square Feet')),
                ('garages', models.IntegerField(default=0)),
                ('completion_year', models.IntegerField(blank=True, help_text='e.g., 2029', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text="Check if this is 'Property of the Month'")),
                ('is_available', models.BooleanField(default=True)),
                ('main_image', models.ImageField(upload_to='property_images/main/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Modern Kitchen, Master Bedroom', max_length=100)),
                ('image', models.ImageField(upload_to='property_images/benefits/')),
                ('description', models.TextField(blank=True, help_text='Short description of the benefit')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='properties.property')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/gallery/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
