# Generated by Django 5.2.14 on 2026-05-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, help_text='Link to YouTube or Virtual Tour', null=True),
        ),
    ]
