# Generated by Django 5.2.14 on 2026-05-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_virtual_tour_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_private',
            field=models.BooleanField(default=False, help_text="Check if this is a 'Private Listing' (requires password)"),
        ),
    ]
