# Generated by Django 5.2.14 on 2026-05-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('land', 'Land'), ('airbnb', 'Airbnb / Short Term')], default='residential', help_text='Select category: Residential, Commercial, or Land', max_length=20),
        ),
    ]
